// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Applications/Management/clients.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.Applications.Management {

  /// <summary>Holder for reflection information generated from Applications/Management/clients.proto</summary>
  public static partial class ClientsReflection {

    #region Descriptor
    /// <summary>File descriptor for Applications/Management/clients.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVBcHBsaWNhdGlvbnMvTWFuYWdlbWVudC9jbGllbnRzLnByb3RvEiBkb2xp",
            "dHRsZS5hcHBsaWNhdGlvbnMubWFuYWdlbWVudBoeQXBwbGljYXRpb25zL2Ns",
            "aWVudF9pbmZvLnByb3RvIhkKF0Nvbm5lY3RlZENsaWVudHNSZXF1ZXN0IlwK",
            "D0Nvbm5lY3RlZENsaWVudBIxCgZDbGllbnQYASABKAsyIS5kb2xpdHRsZS5h",
            "cHBsaWNhdGlvbnMuQ2xpZW50SW5mbxIWCg5Db25uZWN0aW9uVGltZRgCIAEo",
            "AyJeChhDb25uZWN0ZWRDbGllbnRzUmVzcG9uc2USQgoHQ2xpZW50cxgBIAMo",
            "CzIxLmRvbGl0dGxlLmFwcGxpY2F0aW9ucy5tYW5hZ2VtZW50LkNvbm5lY3Rl",
            "ZENsaWVudDKaAQoHQ2xpZW50cxKOAQoTR2V0Q29ubmVjdGVkQ2xpZW50cxI5",
            "LmRvbGl0dGxlLmFwcGxpY2F0aW9ucy5tYW5hZ2VtZW50LkNvbm5lY3RlZENs",
            "aWVudHNSZXF1ZXN0GjouZG9saXR0bGUuYXBwbGljYXRpb25zLm1hbmFnZW1l",
            "bnQuQ29ubmVjdGVkQ2xpZW50c1Jlc3BvbnNlIgBCI6oCIERvbGl0dGxlLkFw",
            "cGxpY2F0aW9ucy5NYW5hZ2VtZW50YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.Applications.ClientInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.Applications.Management.ConnectedClientsRequest), global::Dolittle.Applications.Management.ConnectedClientsRequest.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.Applications.Management.ConnectedClient), global::Dolittle.Applications.Management.ConnectedClient.Parser, new[]{ "Client", "ConnectionTime" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.Applications.Management.ConnectedClientsResponse), global::Dolittle.Applications.Management.ConnectedClientsResponse.Parser, new[]{ "Clients" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConnectedClientsRequest : pb::IMessage<ConnectedClientsRequest> {
    private static readonly pb::MessageParser<ConnectedClientsRequest> _parser = new pb::MessageParser<ConnectedClientsRequest>(() => new ConnectedClientsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConnectedClientsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.Applications.Management.ClientsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectedClientsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectedClientsRequest(ConnectedClientsRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectedClientsRequest Clone() {
      return new ConnectedClientsRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConnectedClientsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConnectedClientsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConnectedClientsRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class ConnectedClient : pb::IMessage<ConnectedClient> {
    private static readonly pb::MessageParser<ConnectedClient> _parser = new pb::MessageParser<ConnectedClient>(() => new ConnectedClient());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConnectedClient> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.Applications.Management.ClientsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectedClient() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectedClient(ConnectedClient other) : this() {
      client_ = other.client_ != null ? other.client_.Clone() : null;
      connectionTime_ = other.connectionTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectedClient Clone() {
      return new ConnectedClient(this);
    }

    /// <summary>Field number for the "Client" field.</summary>
    public const int ClientFieldNumber = 1;
    private global::Dolittle.Applications.ClientInfo client_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.Applications.ClientInfo Client {
      get { return client_; }
      set {
        client_ = value;
      }
    }

    /// <summary>Field number for the "ConnectionTime" field.</summary>
    public const int ConnectionTimeFieldNumber = 2;
    private long connectionTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ConnectionTime {
      get { return connectionTime_; }
      set {
        connectionTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConnectedClient);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConnectedClient other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Client, other.Client)) return false;
      if (ConnectionTime != other.ConnectionTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (client_ != null) hash ^= Client.GetHashCode();
      if (ConnectionTime != 0L) hash ^= ConnectionTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (client_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Client);
      }
      if (ConnectionTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ConnectionTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (client_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Client);
      }
      if (ConnectionTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ConnectionTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConnectedClient other) {
      if (other == null) {
        return;
      }
      if (other.client_ != null) {
        if (client_ == null) {
          Client = new global::Dolittle.Applications.ClientInfo();
        }
        Client.MergeFrom(other.Client);
      }
      if (other.ConnectionTime != 0L) {
        ConnectionTime = other.ConnectionTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (client_ == null) {
              Client = new global::Dolittle.Applications.ClientInfo();
            }
            input.ReadMessage(Client);
            break;
          }
          case 16: {
            ConnectionTime = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ConnectedClientsResponse : pb::IMessage<ConnectedClientsResponse> {
    private static readonly pb::MessageParser<ConnectedClientsResponse> _parser = new pb::MessageParser<ConnectedClientsResponse>(() => new ConnectedClientsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConnectedClientsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.Applications.Management.ClientsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectedClientsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectedClientsResponse(ConnectedClientsResponse other) : this() {
      clients_ = other.clients_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectedClientsResponse Clone() {
      return new ConnectedClientsResponse(this);
    }

    /// <summary>Field number for the "Clients" field.</summary>
    public const int ClientsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Dolittle.Applications.Management.ConnectedClient> _repeated_clients_codec
        = pb::FieldCodec.ForMessage(10, global::Dolittle.Applications.Management.ConnectedClient.Parser);
    private readonly pbc::RepeatedField<global::Dolittle.Applications.Management.ConnectedClient> clients_ = new pbc::RepeatedField<global::Dolittle.Applications.Management.ConnectedClient>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Dolittle.Applications.Management.ConnectedClient> Clients {
      get { return clients_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConnectedClientsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConnectedClientsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!clients_.Equals(other.clients_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= clients_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      clients_.WriteTo(output, _repeated_clients_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += clients_.CalculateSize(_repeated_clients_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConnectedClientsResponse other) {
      if (other == null) {
        return;
      }
      clients_.Add(other.clients_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            clients_.AddEntriesFrom(input, _repeated_clients_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
