// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Events.Relativity/Microservice/quantum_tunnel.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.Runtime.Events.Relativity.Microservice {

  /// <summary>Holder for reflection information generated from Events.Relativity/Microservice/quantum_tunnel.proto</summary>
  public static partial class QuantumTunnelReflection {

    #region Descriptor
    /// <summary>File descriptor for Events.Relativity/Microservice/quantum_tunnel.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QuantumTunnelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNFdmVudHMuUmVsYXRpdml0eS9NaWNyb3NlcnZpY2UvcXVhbnR1bV90dW5u",
            "ZWwucHJvdG8SJ2RvbGl0dGxlLmV2ZW50cy5yZWxhdGl2aXR5Lm1pY3Jvc2Vy",
            "dmljZRowRXZlbnRzLlJlbGF0aXZpdHkvTWljcm9zZXJ2aWNlL29wZW5fdHVu",
            "bmVsLnByb3RvGkhFdmVudHMuUmVsYXRpdml0eS9NaWNyb3NlcnZpY2UvY29t",
            "bWl0dGVkX2V2ZW50X3N0cmVhbV93aXRoX2NvbnRleHQucHJvdG8yogEKFFF1",
            "YW50dW1UdW5uZWxTZXJ2aWNlEokBCgRPcGVuEjMuZG9saXR0bGUuZXZlbnRz",
            "LnJlbGF0aXZpdHkubWljcm9zZXJ2aWNlLk9wZW5UdW5uZWwaSC5kb2xpdHRs",
            "ZS5ldmVudHMucmVsYXRpdml0eS5taWNyb3NlcnZpY2UuQ29tbWl0dGVkRXZl",
            "bnRTdHJlYW1XaXRoQ29udGV4dCIAMAFCMqoCL0RvbGl0dGxlLlJ1bnRpbWUu",
            "RXZlbnRzLlJlbGF0aXZpdHkuTWljcm9zZXJ2aWNlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.Runtime.Events.Relativity.Microservice.OpenTunnelReflection.Descriptor, global::Dolittle.Runtime.Events.Relativity.Microservice.CommittedEventStreamWithContextReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
