// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Events.Relativity/Microservice/versioned_event_source.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.Events.Relativity.Microservice {

  /// <summary>Holder for reflection information generated from Events.Relativity/Microservice/versioned_event_source.proto</summary>
  public static partial class VersionedEventSourceReflection {

    #region Descriptor
    /// <summary>File descriptor for Events.Relativity/Microservice/versioned_event_source.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VersionedEventSourceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjtFdmVudHMuUmVsYXRpdml0eS9NaWNyb3NlcnZpY2UvdmVyc2lvbmVkX2V2",
            "ZW50X3NvdXJjZS5wcm90bxInZG9saXR0bGUuZXZlbnRzLnJlbGF0aXZpdHku",
            "bWljcm9zZXJ2aWNlGjlFdmVudHMuUmVsYXRpdml0eS9NaWNyb3NlcnZpY2Uv",
            "ZXZlbnRfc291cmNlX3ZlcnNpb24ucHJvdG8iiwEKFFZlcnNpb25lZEV2ZW50",
            "U291cmNlEkwKB3ZlcnNpb24YASABKAsyOy5kb2xpdHRsZS5ldmVudHMucmVs",
            "YXRpdml0eS5taWNyb3NlcnZpY2UuRXZlbnRTb3VyY2VWZXJzaW9uEhMKC2V2",
            "ZW50U291cmNlGAIgASgMEhAKCGFydGlmYWN0GAMgASgMQiqqAidEb2xpdHRs",
            "ZS5FdmVudHMuUmVsYXRpdml0eS5NaWNyb3NlcnZpY2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.Events.Relativity.Microservice.EventSourceVersionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.Events.Relativity.Microservice.VersionedEventSource), global::Dolittle.Events.Relativity.Microservice.VersionedEventSource.Parser, new[]{ "Version", "EventSource", "Artifact" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Represents a versioned event source
  /// </summary>
  public sealed partial class VersionedEventSource : pb::IMessage<VersionedEventSource> {
    private static readonly pb::MessageParser<VersionedEventSource> _parser = new pb::MessageParser<VersionedEventSource>(() => new VersionedEventSource());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VersionedEventSource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.Events.Relativity.Microservice.VersionedEventSourceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VersionedEventSource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VersionedEventSource(VersionedEventSource other) : this() {
      version_ = other.version_ != null ? other.version_.Clone() : null;
      eventSource_ = other.eventSource_;
      artifact_ = other.artifact_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VersionedEventSource Clone() {
      return new VersionedEventSource(this);
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 1;
    private global::Dolittle.Events.Relativity.Microservice.EventSourceVersion version_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.Events.Relativity.Microservice.EventSourceVersion Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "eventSource" field.</summary>
    public const int EventSourceFieldNumber = 2;
    private pb::ByteString eventSource_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString EventSource {
      get { return eventSource_; }
      set {
        eventSource_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "artifact" field.</summary>
    public const int ArtifactFieldNumber = 3;
    private pb::ByteString artifact_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Artifact {
      get { return artifact_; }
      set {
        artifact_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VersionedEventSource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VersionedEventSource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Version, other.Version)) return false;
      if (EventSource != other.EventSource) return false;
      if (Artifact != other.Artifact) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (version_ != null) hash ^= Version.GetHashCode();
      if (EventSource.Length != 0) hash ^= EventSource.GetHashCode();
      if (Artifact.Length != 0) hash ^= Artifact.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (version_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Version);
      }
      if (EventSource.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(EventSource);
      }
      if (Artifact.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Artifact);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (version_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Version);
      }
      if (EventSource.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(EventSource);
      }
      if (Artifact.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Artifact);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VersionedEventSource other) {
      if (other == null) {
        return;
      }
      if (other.version_ != null) {
        if (version_ == null) {
          Version = new global::Dolittle.Events.Relativity.Microservice.EventSourceVersion();
        }
        Version.MergeFrom(other.Version);
      }
      if (other.EventSource.Length != 0) {
        EventSource = other.EventSource;
      }
      if (other.Artifact.Length != 0) {
        Artifact = other.Artifact;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (version_ == null) {
              Version = new global::Dolittle.Events.Relativity.Microservice.EventSourceVersion();
            }
            input.ReadMessage(Version);
            break;
          }
          case 18: {
            EventSource = input.ReadBytes();
            break;
          }
          case 26: {
            Artifact = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
