// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Events.Relativity/interaction/committed_event_stream_with_context.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.Runtime.Events.Relativity.Interaction.Grpc {

  /// <summary>Holder for reflection information generated from Events.Relativity/interaction/committed_event_stream_with_context.proto</summary>
  public static partial class CommittedEventStreamWithContextReflection {

    #region Descriptor
    /// <summary>File descriptor for Events.Relativity/interaction/committed_event_stream_with_context.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommittedEventStreamWithContextReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkdFdmVudHMuUmVsYXRpdml0eS9pbnRlcmFjdGlvbi9jb21taXR0ZWRfZXZl",
            "bnRfc3RyZWFtX3dpdGhfY29udGV4dC5wcm90bxIaZG9saXR0bGUuZXZlbnRz",
            "LnJlbGF0aXZpdHkaOkV2ZW50cy5SZWxhdGl2aXR5L2ludGVyYWN0aW9uL2Nv",
            "bW1pdHRlZF9ldmVudF9zdHJlYW0ucHJvdG8aNUV2ZW50cy5SZWxhdGl2aXR5",
            "L2ludGVyYWN0aW9uL2V4ZWN1dGlvbl9jb250ZXh0LnByb3RvIqIBCh9Db21t",
            "aXR0ZWRFdmVudFN0cmVhbVdpdGhDb250ZXh0EkAKBmNvbW1pdBgBIAEoCzIw",
            "LmRvbGl0dGxlLmV2ZW50cy5yZWxhdGl2aXR5LkNvbW1pdHRlZEV2ZW50U3Ry",
            "ZWFtEj0KB2NvbnRleHQYAiABKAsyLC5kb2xpdHRsZS5ldmVudHMucmVsYXRp",
            "dml0eS5FeGVjdXRpb25Db250ZXh0QjaqAjNEb2xpdHRsZS5SdW50aW1lLkV2",
            "ZW50cy5SZWxhdGl2aXR5LkludGVyYWN0aW9uLkdycGNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.CommittedEventStreamReflection.Descriptor, global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.ExecutionContextReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.CommittedEventStreamWithContext), global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.CommittedEventStreamWithContext.Parser, new[]{ "Commit", "Context" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Represents a committed event stream with the Execution Context
  /// </summary>
  public sealed partial class CommittedEventStreamWithContext : pb::IMessage<CommittedEventStreamWithContext> {
    private static readonly pb::MessageParser<CommittedEventStreamWithContext> _parser = new pb::MessageParser<CommittedEventStreamWithContext>(() => new CommittedEventStreamWithContext());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CommittedEventStreamWithContext> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.CommittedEventStreamWithContextReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommittedEventStreamWithContext() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommittedEventStreamWithContext(CommittedEventStreamWithContext other) : this() {
      commit_ = other.commit_ != null ? other.commit_.Clone() : null;
      context_ = other.context_ != null ? other.context_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommittedEventStreamWithContext Clone() {
      return new CommittedEventStreamWithContext(this);
    }

    /// <summary>Field number for the "commit" field.</summary>
    public const int CommitFieldNumber = 1;
    private global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.CommittedEventStream commit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.CommittedEventStream Commit {
      get { return commit_; }
      set {
        commit_ = value;
      }
    }

    /// <summary>Field number for the "context" field.</summary>
    public const int ContextFieldNumber = 2;
    private global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.ExecutionContext context_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.ExecutionContext Context {
      get { return context_; }
      set {
        context_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CommittedEventStreamWithContext);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CommittedEventStreamWithContext other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Commit, other.Commit)) return false;
      if (!object.Equals(Context, other.Context)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (commit_ != null) hash ^= Commit.GetHashCode();
      if (context_ != null) hash ^= Context.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (commit_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Commit);
      }
      if (context_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Context);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (commit_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Commit);
      }
      if (context_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Context);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CommittedEventStreamWithContext other) {
      if (other == null) {
        return;
      }
      if (other.commit_ != null) {
        if (commit_ == null) {
          Commit = new global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.CommittedEventStream();
        }
        Commit.MergeFrom(other.Commit);
      }
      if (other.context_ != null) {
        if (context_ == null) {
          Context = new global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.ExecutionContext();
        }
        Context.MergeFrom(other.Context);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (commit_ == null) {
              Commit = new global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.CommittedEventStream();
            }
            input.ReadMessage(Commit);
            break;
          }
          case 18: {
            if (context_ == null) {
              Context = new global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.ExecutionContext();
            }
            input.ReadMessage(Context);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
