// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Events.Relativity/interaction/event_metadata.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.Runtime.Events.Relativity.Interaction.Grpc {

  /// <summary>Holder for reflection information generated from Events.Relativity/interaction/event_metadata.proto</summary>
  public static partial class EventMetadataReflection {

    #region Descriptor
    /// <summary>File descriptor for Events.Relativity/interaction/event_metadata.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventMetadataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjJFdmVudHMuUmVsYXRpdml0eS9pbnRlcmFjdGlvbi9ldmVudF9tZXRhZGF0",
            "YS5wcm90bxIaZG9saXR0bGUuZXZlbnRzLnJlbGF0aXZpdHkaEXN5c3RlbS9n",
            "dWlkLnByb3RvGixFdmVudHMuUmVsYXRpdml0eS9pbnRlcmFjdGlvbi9hcnRp",
            "ZmFjdC5wcm90bxo6RXZlbnRzLlJlbGF0aXZpdHkvaW50ZXJhY3Rpb24vdmVy",
            "c2lvbmVkX2V2ZW50X3NvdXJjZS5wcm90bxo0RXZlbnRzLlJlbGF0aXZpdHkv",
            "aW50ZXJhY3Rpb24vb3JpZ2luYWxfY29udGV4dC5wcm90byKpAgoNRXZlbnRN",
            "ZXRhZGF0YRIfCgdldmVudElkGAEgASgLMg4uZG9saXR0bGUuZ3VpZBJACgZz",
            "b3VyY2UYAiABKAsyMC5kb2xpdHRsZS5ldmVudHMucmVsYXRpdml0eS5WZXJz",
            "aW9uZWRFdmVudFNvdXJjZRIlCg1jb3JyZWxhdGlvbklkGAMgASgLMg4uZG9s",
            "aXR0bGUuZ3VpZBI2CghhcnRpZmFjdBgEIAEoCzIkLmRvbGl0dGxlLmV2ZW50",
            "cy5yZWxhdGl2aXR5LkFydGlmYWN0EhAKCG9jY3VycmVkGAUgASgDEkQKD29y",
            "aWdpbmFsQ29udGV4dBgGIAEoCzIrLmRvbGl0dGxlLmV2ZW50cy5yZWxhdGl2",
            "aXR5Lk9yaWdpbmFsQ29udGV4dEI2qgIzRG9saXR0bGUuUnVudGltZS5FdmVu",
            "dHMuUmVsYXRpdml0eS5JbnRlcmFjdGlvbi5HcnBjYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::System.Protobuf.GuidReflection.Descriptor, global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.ArtifactReflection.Descriptor, global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.VersionedEventSourceReflection.Descriptor, global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.OriginalContextReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.EventMetadata), global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.EventMetadata.Parser, new[]{ "EventId", "Source", "CorrelationId", "Artifact", "Occurred", "OriginalContext" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Represents the metadata related to an event
  /// </summary>
  public sealed partial class EventMetadata : pb::IMessage<EventMetadata> {
    private static readonly pb::MessageParser<EventMetadata> _parser = new pb::MessageParser<EventMetadata>(() => new EventMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EventMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.EventMetadataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventMetadata(EventMetadata other) : this() {
      eventId_ = other.eventId_ != null ? other.eventId_.Clone() : null;
      source_ = other.source_ != null ? other.source_.Clone() : null;
      correlationId_ = other.correlationId_ != null ? other.correlationId_.Clone() : null;
      artifact_ = other.artifact_ != null ? other.artifact_.Clone() : null;
      occurred_ = other.occurred_;
      originalContext_ = other.originalContext_ != null ? other.originalContext_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventMetadata Clone() {
      return new EventMetadata(this);
    }

    /// <summary>Field number for the "eventId" field.</summary>
    public const int EventIdFieldNumber = 1;
    private global::System.Protobuf.guid eventId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::System.Protobuf.guid EventId {
      get { return eventId_; }
      set {
        eventId_ = value;
      }
    }

    /// <summary>Field number for the "source" field.</summary>
    public const int SourceFieldNumber = 2;
    private global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.VersionedEventSource source_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.VersionedEventSource Source {
      get { return source_; }
      set {
        source_ = value;
      }
    }

    /// <summary>Field number for the "correlationId" field.</summary>
    public const int CorrelationIdFieldNumber = 3;
    private global::System.Protobuf.guid correlationId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::System.Protobuf.guid CorrelationId {
      get { return correlationId_; }
      set {
        correlationId_ = value;
      }
    }

    /// <summary>Field number for the "artifact" field.</summary>
    public const int ArtifactFieldNumber = 4;
    private global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.Artifact artifact_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.Artifact Artifact {
      get { return artifact_; }
      set {
        artifact_ = value;
      }
    }

    /// <summary>Field number for the "occurred" field.</summary>
    public const int OccurredFieldNumber = 5;
    private long occurred_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Occurred {
      get { return occurred_; }
      set {
        occurred_ = value;
      }
    }

    /// <summary>Field number for the "originalContext" field.</summary>
    public const int OriginalContextFieldNumber = 6;
    private global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.OriginalContext originalContext_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.OriginalContext OriginalContext {
      get { return originalContext_; }
      set {
        originalContext_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EventMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EventMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(EventId, other.EventId)) return false;
      if (!object.Equals(Source, other.Source)) return false;
      if (!object.Equals(CorrelationId, other.CorrelationId)) return false;
      if (!object.Equals(Artifact, other.Artifact)) return false;
      if (Occurred != other.Occurred) return false;
      if (!object.Equals(OriginalContext, other.OriginalContext)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (eventId_ != null) hash ^= EventId.GetHashCode();
      if (source_ != null) hash ^= Source.GetHashCode();
      if (correlationId_ != null) hash ^= CorrelationId.GetHashCode();
      if (artifact_ != null) hash ^= Artifact.GetHashCode();
      if (Occurred != 0L) hash ^= Occurred.GetHashCode();
      if (originalContext_ != null) hash ^= OriginalContext.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (eventId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(EventId);
      }
      if (source_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Source);
      }
      if (correlationId_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CorrelationId);
      }
      if (artifact_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Artifact);
      }
      if (Occurred != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Occurred);
      }
      if (originalContext_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(OriginalContext);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (eventId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EventId);
      }
      if (source_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Source);
      }
      if (correlationId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CorrelationId);
      }
      if (artifact_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Artifact);
      }
      if (Occurred != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Occurred);
      }
      if (originalContext_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OriginalContext);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EventMetadata other) {
      if (other == null) {
        return;
      }
      if (other.eventId_ != null) {
        if (eventId_ == null) {
          EventId = new global::System.Protobuf.guid();
        }
        EventId.MergeFrom(other.EventId);
      }
      if (other.source_ != null) {
        if (source_ == null) {
          Source = new global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.VersionedEventSource();
        }
        Source.MergeFrom(other.Source);
      }
      if (other.correlationId_ != null) {
        if (correlationId_ == null) {
          CorrelationId = new global::System.Protobuf.guid();
        }
        CorrelationId.MergeFrom(other.CorrelationId);
      }
      if (other.artifact_ != null) {
        if (artifact_ == null) {
          Artifact = new global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.Artifact();
        }
        Artifact.MergeFrom(other.Artifact);
      }
      if (other.Occurred != 0L) {
        Occurred = other.Occurred;
      }
      if (other.originalContext_ != null) {
        if (originalContext_ == null) {
          OriginalContext = new global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.OriginalContext();
        }
        OriginalContext.MergeFrom(other.OriginalContext);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (eventId_ == null) {
              EventId = new global::System.Protobuf.guid();
            }
            input.ReadMessage(EventId);
            break;
          }
          case 18: {
            if (source_ == null) {
              Source = new global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.VersionedEventSource();
            }
            input.ReadMessage(Source);
            break;
          }
          case 26: {
            if (correlationId_ == null) {
              CorrelationId = new global::System.Protobuf.guid();
            }
            input.ReadMessage(CorrelationId);
            break;
          }
          case 34: {
            if (artifact_ == null) {
              Artifact = new global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.Artifact();
            }
            input.ReadMessage(Artifact);
            break;
          }
          case 40: {
            Occurred = input.ReadInt64();
            break;
          }
          case 50: {
            if (originalContext_ == null) {
              OriginalContext = new global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.OriginalContext();
            }
            input.ReadMessage(OriginalContext);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
