// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Events.Relativity/interaction/quantum_tunnel.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dolittle.Runtime.Events.Relativity.Interaction.Grpc {

  /// <summary>Holder for reflection information generated from Events.Relativity/interaction/quantum_tunnel.proto</summary>
  public static partial class QuantumTunnelReflection {

    #region Descriptor
    /// <summary>File descriptor for Events.Relativity/interaction/quantum_tunnel.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QuantumTunnelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjJFdmVudHMuUmVsYXRpdml0eS9pbnRlcmFjdGlvbi9xdWFudHVtX3R1bm5l",
            "bC5wcm90bxIaZG9saXR0bGUuZXZlbnRzLnJlbGF0aXZpdHkaL0V2ZW50cy5S",
            "ZWxhdGl2aXR5L2ludGVyYWN0aW9uL29wZW5fdHVubmVsLnByb3RvGkdFdmVu",
            "dHMuUmVsYXRpdml0eS9pbnRlcmFjdGlvbi9jb21taXR0ZWRfZXZlbnRfc3Ry",
            "ZWFtX3dpdGhfY29udGV4dC5wcm90bzKHAQoUUXVhbnR1bVR1bm5lbFNlcnZp",
            "Y2USbwoET3BlbhImLmRvbGl0dGxlLmV2ZW50cy5yZWxhdGl2aXR5Lk9wZW5U",
            "dW5uZWwaOy5kb2xpdHRsZS5ldmVudHMucmVsYXRpdml0eS5Db21taXR0ZWRF",
            "dmVudFN0cmVhbVdpdGhDb250ZXh0IgAwAUI2qgIzRG9saXR0bGUuUnVudGlt",
            "ZS5FdmVudHMuUmVsYXRpdml0eS5JbnRlcmFjdGlvbi5HcnBjYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.OpenTunnelReflection.Descriptor, global::Dolittle.Runtime.Events.Relativity.Interaction.Grpc.CommittedEventStreamWithContextReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
